Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.cpus = 1
    vb.memory = 2048
  end
  
  config.vm.hostname = "sclolusS"
  config.vm.network "private_network", ip: "192.168.56.110", brigde: "wlp36s0"
  
  config.vm.provision "shell", path: "./scripts/k3s_controller_setup.sh"
  config.vm.provision "shell", path: "./scripts/ssh_setup.sh"
  config.vm.provision "file", source: "./configs/", destination: "/home/vagrant/configs", run: "always"
end
